### ISSUE TITLE
KHagan_Peer Review

### ISSUE THREAD

**Issue by hagankf** [karlenaochoa/rclassproject#4]
@datalorax
@kdenning 
@tamaraniella 
@karlenaochoa 

Hello! 

Thank you for the opportunity to review your data prep script. It is great that you have your data prep script already embedded in the APA-based template, and you look to be well on your way towards having a polished script and well-curated graphs! I made comments in the RMD file (with KH: immediately before each comment), but more overarching feedback is below:

Coding style: I thought the titles of the chunk headers (“setup,” “import and clean,” and “tidydata,” for example) made it easy to quickly apprehend what each code chunk was doing, and this is a change that I will definitely make to my own code! I also note in the body of the RMD file that the set-up for the three different plots is done the same way each time, and each plot (and the prep specific to that plot) is in its own code chunk. That sets up a pattern or convention that is easy for the reader to track and adopt on their own if they wishes. I followed along easily and was able to deduce the aim of each line of code from the code itself, but comments would likely be helpful if your code was intended for a reader that was unfamiliar with our current code repertoire or the aims of tidying data. 

Coding strategy: The coding strategy clearly makes use of the verbs that we have acquired, and you rightly use the gather() function to address the columns that have a second variable (e.g., trial number) embedded in the variable name. I noted two uses of as.numeric() where the vector is already numeric, but this could be seen as a measure to anticipate and prevent potential error. Other measures to prevent error or confirm that your code has done what you intend (in addition to checking the updated/new data frame, of course) could be to use the count() function to make sure that you do not have unintended redundancies (e.g., by counting subject IDs or number of children in each age group). You could also use the levels() function to confirm that your factors have the intended number of levels or str() to take a look at the parameters of your data set and the way that R is characterizing each column.

Presentation: graphs: Your graphs do a nice job of treating one question per graph. My only recommendation was to add error bars to the bar graph and to alter the subtitle in one graph to instead include information in the figure caption. When you finalize the graphs for your paper you’ll likely add “Figure 1.” to the title for the first graph, and so on for the other graphs. 

Presentation: table: It’s great that you use the kable options to style the table. It may be helpful to include information about the units that the “first-hand” and “second-hand” columns are referring to. That info may go into the title for the table once you have the table.  

Achievement, mastery, cleverness, creativity: I noted a line of code that I did not yet know how to use, and that code will be helpful to me moving forward. Your code demonstrates mastery of the verbs that we have been using to import, clean, tidy, and visualize data!

Ease of access: Code is very well organized. Everything ran seamlessly, and reviewing your code helped me to further appreciate how embedding data and RMD files in projects could make data sharing and exercises in reproducing analysis much, much easier.

**Comment by datalorax** [comment]
Hi Katherine, 

Your summary here is great. In it you state 

> I made comments in the RMD file (with KH: immediately before each comment), but more overarching feedback is below:

I'm not sure I follow where you provided these comments. Can you maybe fork the repo and push your comments to that fork?

I actually think the Figure 1 part should happen automatically with {papaja} and if you put `fig.cap = "My figure caption"` in the code chunk options then it will put whatever caption you want. So you probably don't actually want the figure caption to be in the title of the plot, in this case.

Overall, this looks like great feedback, but it would be good if you can share the comments you mention as well.
