### ISSUE TITLE
Problem Pulling the latest changes

### ISSUE THREAD

**Issue by tamaraniella** [karlenaochoa/rclassproject#7]
@datalorax 
Hi! I am having some issues pulling the latest changes to be able to start working on my part. I run into the following warning when I try to pull: 

> >>> C:/Program Files/Git/bin/git.exe pull
error: The following untracked working tree files would be overwritten by merge:
	script/final_proj_script_files/figure-latex/plot 1-1.pdf
	script/final_proj_script_files/figure-latex/plot 1-1.png
Please move or remove them before you merge.
Aborting

I deleted all the elements in the figure-latex file (pdfs and pngs) but the plot 1-1 wasn't even there, so I still run into the same error. Do you know what other way I could solve this? 

Thank you!!

**Comment by datalorax** [comment]
Hi Tamara,

Move script/final_proj_script_files/figure-latex/plot 1-1.pdf  and script/final_proj_script_files/figure-latex/plot 1-1.png to your desktop, then try to pull again. Do you still get the error?

Thanks,
--
Daniel Anderson
Research Assistant Professor
Behavioral Research and Teaching
University of Oregon

**Comment by tamaraniella** [comment]
Thanks for the quick response! That worked - I was not finding the files because I was just looking at the folders in R studio. 

Thank you!
@datalorax
